namespace OpenSpaceCodeGen.AITypes {
    public enum EnumKeyword {
        If,
        IfNot,
        If2,
        If4,
        If8,
        If16,
        If32,
        If64,
        IfNot2,
        IfNot4,
        IfNot8,
        IfNot16,
        IfNot32,
        IfNot64,
        IfDebug ,
        IfNotU64 ,
        Then,
        Else,
        EngineGoto,
        Me,
        MainActor,
        Nobody,
        NoInput,
        NoSoundEvent,
        NoSuperObject,
        Nowhere,
        NoSOLinksWord ,
        EmptyText,
        CapsNull,
        NoGraph,
        NoAction,
        NoGMT,
        NoVMT,
        While,
        BeginWhile,
        EndWhile,
        World,
        Noway,
        Goto
    }
}
